Tokenizer
Functions
bool is_ident_char (int c)
check if character is part of an identifier.
bool is_binary_char (int c)
bool src_clear ()
bool src_add (const char *line)
bool src_read (const char *name)
bool src_dump ()
bool readLine ()
read one line from stdin stores the result into gd.line.
bool readChar (char *t)
read one character from input and store it somewhere.
bool readStringToken (void)
read string token.
void parse_verbatim (char c)
bool nextToken (void)
read next token.
Detailed Description
convert stdin into tokens. each token is returned by the call to
See also
nextToken.
Function Documentation
is_binary_char()
bool is_binary_char (int c)
binary chars are special ones for binary message names
                             {
    switch (c) {
        case '!':
        case '%':
        case '&':
        case '*':
        case '+':
        case ',':
        case '/':
        case '<':
        case '=':
        case '>':
        case '?':
        case '@':
        case '\\':
        case '~':
        case '|': // sollte laut Vorschlag ein Binary Operator sein. Kollidiert aber mit der temporary declaration.
// das muss dann wohl auf der Syntaxebene geklärt werden.
        case '-':
            return true;
        default:
            return false;
    }
}
Referenced by nextToken().
is_ident_char()
bool is_ident_char (int c)
check if character is part of an identifier.
Parameters
 in c character to classify.
Returns
true if if c is an identifier character.
                            {
    return isalpha(c) || isdigit(c) || c == '_';
}
Referenced by nextToken().
nextToken()
bool nextToken ()
read next token.
This is a more detailed description.
Returns
true if successful
                   {
    char c;
    bool result = false;
    while(true) {
        while(readChar(&c) && isspace(c));
        if(c == '"') {
            while(readChar(&c) && c != '"');
        }
        else
            break;
    }
    if(gd.state == 1) {
        if(isalpha(c)) {
            int idx = 0;
            for(;;) {
                gd.buf[idx++] = c;
                readChar(&c);
                if(!is_ident_char(c))
                    break;
            }
            if(c == ':') {
                gd.buf[idx++] = c;
                gd.token = TK_KEYWORD;
            }
            else {
                gd.pos--;
                gd.token = TK_IDENT;
            }
            gd.buf[idx] = 0;
            result = true;
        }
        else if(is_binary_char(c)) {
            for(int idx = 0; is_binary_char(c); idx++) {
                gd.buf[idx] = c;
                gd.buf[idx + 1] = 0;
                readChar(&c);
            }
            gd.pos--;
            gd.token = 0;
            gd.token = TK_BINOP;
            result = true;
            if(strcmp(":=", gd.buf) == 0) {
                gd.token = TK_ASSIGN;
                result = true;
            }
            else if(strcmp("<-", gd.buf) == 0) {
                gd.token = TK_LARROW;
                result = true;
            }
            else if(strcmp("|", gd.buf) == 0) {
                gd.token = TK_BAR;
                result = true;
            }
            else if(0 == strcmp("<", gd.buf)) {
                gd.token = TK_LT;
                result = true;
            }
            else if(0 == strcmp(">", gd.buf)) {
                gd.token = TK_GT;
                result = true;
            }
        }
        else if(isdigit(c)) {
            int idx = 0;
            while(isdigit(c)) {
                printf("### digit %c\n", c);
                gd.buf[idx++] = c;
                gd.buf[idx] = 0;
                readChar(&c);
            }
            gd.pos--;
            gd.token = TK_NUMBER;
            result = true;
        }
        else {
            switch (c) {
                case '\'':
                    result = readStringToken();
                    break;
                case '.':
                    result = true;
                    gd.token = TK_DOT;
                    break;
                case ';':
                    result = true;
                    gd.token = TK_SEMICOLON;
                    break;
                case '(':
                    result = true;
                    gd.token = TK_LPAREN;
                    break;
                case ')':
                    result = true;
                    gd.token = TK_RPAREN;
                    break;
                case '[':
                    result = true;
                    gd.token = TK_LBRACK;
                    break;
                case ']':
                    result = true;
                    gd.token = TK_RBRACK;
                    break;
                case '{':
                    result = true;
                    gd.token = TK_LBRACE;
                    break;
                case '}':
                    result = true;
                    gd.token = TK_RBRACE;
                    break;
                case '#':
                    readChar(&c);
                    for(int idx = 0; is_ident_char(c) || c == ':'; idx++) {
                        gd.buf[idx] = c;
                        gd.buf[idx + 1] = 0;
                        readChar(&c);
                    }
                    gd.pos--;
                    gd.token = TK_SYMBOL;
                    result = true;
                    break;
                case '^':
                    result = true;
                    gd.token = TK_UARROW;
                    break;
                case ':':
                    result = true;
                    gd.token = TK_COLON;
                    readChar(&c);
                    if(c == '=') {
                        gd.token = TK_ASSIGN;
                    }
                    else
                        gd.pos--;
                    break;
                case '$':
                    result = true;
                    gd.token = TK_CHAR;
                    readChar(&c);
                    gd.buf[0] = c;
                    gd.buf[1] = 0;
                    break;
                default:
                    gd.pos--;
                    break;
            }
        }
    }
    return result;
}
References gd::buf, is_binary_char(), is_ident_char(), gd::pos, readChar(), readStringToken(), gd::state, and gd::token.
parse_verbatim()
void parse_verbatim (char c)
parse the verbatim chars (not used)
                              {
    int i = 0;
    gd.buf[i] = 0;
    readChar(&c);
    while(c != '}') {
        gd.buf[i++] = c;
        gd.buf[i] = 0;
        readChar(&c);
    }
    gd.token = TK_VERBATIM;
}
References gd::buf, readChar(), and gd::token.
readChar()
bool readChar (char * t)
read one character from input and store it somewhere.
Parameters
 in t c-string of some sort.
Returns
true if successful
                         {
    bool result = true;
    if(gd.state == 0) {
        result = readLine();
    }
    if(result) {
        *t = gd.line[gd.pos++];
        while(*t == 0) {
            if(readLine()) {
                *t = gd.line[gd.pos++];
            }
            else {
                result = false;
                break;
            }
        }
    }
    return result;
}
References gd::line, gd::pos, readLine(), and gd::state.
Referenced by nextToken(), parse_verbatim(), and readStringToken().
readLine()
bool readLine ()
read one line from stdin stores the result into gd.line.
trailing blanks are removed.
                  {
    if(gd.src_iter == NULL) {
        gd.src_iter = itab_foreach(gd.src);
    }
    else {
        gd.src_iter = itab_next(gd.src_iter);
    }
    if(gd.src_iter) {
        gd.line = itab_value(gd.src_iter);
        gd.line_count++;
        printf("%2d:%s\n", gd.line_count, gd.line);
        gd.pos = 0;
        gd.state = 1;
        return true;
    }
    else {
        gd.line = "";
        gd.state = 2;
        return false;
    }
}
References itab_foreach(), itab_next(), itab_value(), gd::line, gd::line_count, gd::pos, gd::src, gd::src_iter, and gd::state.
Referenced by readChar().
readStringToken()
bool readStringToken (void)
read string token.
Returns
true if successful
                         {
    int idx = 0;
    char c;
    while(readChar(&c) && '\'' != c) {
        if(c == '\\')
            readChar(&c);
        gd.buf[idx++] = c;
    }
    gd.buf[idx] = 0;
    gd.token = TK_STRING;
    return true;
}
References gd::buf, readChar(), and gd::token.
Referenced by nextToken().
src_add()
bool src_add (const char *)
adding one line to the source that will be parsed.
                                 {
    int n = itab_lines(gd.src);
    char buf[10];
    sprintf(buf, "%09d", n + 1);
    itab_append(gd.src, buf, talloc_strdup(gd.src, line));
}
References itab_append(), itab_lines(), and gd::src.
src_clear()
bool src_clear ()
clear and initialize the source that will alter be parsed.
needs to be called before using src_add. src_read will do it automatically.
                   {
    if(gd.src) {
        talloc_free(gd.src);
    }
    gd.src = itab_new();
    if(gd.src_iter) {
        talloc_free(gd.src_iter);
    }
    gd.src_iter = NULL;
}
References itab_new(), gd::src, and gd::src_iter.
Referenced by src_read().
src_dump()
bool src_dump ()
dumps all the lines of the current source.
                  {
    for(struct itab_iter * x = itab_foreach(gd.src);
         x; x = itab_next(x)) {
        printf("%s:%s\n", itab_key(x), itab_value(x));
    }
}
References itab_foreach(), itab_key(), itab_next(), itab_value(), and gd::src.
src_read()
bool src_read (const char * name)
read file into itab.
read a file into src itab.
                                  {
    FILE *f = fopen(name, "r");
    char buf[1000];
    char *line;
    int line_no = 1;
    src_clear();
    for(;;) {
        line = fgets(buf, sizeof(buf), f);
        if(line == NULL)
            break;
        int n = strlen(line);
        while(n > 0 && isspace(line[--n]))
            line[n] = 0;
        char line_number[10];
        sprintf(line_number, "%09d", line_no);
        itab_append(gd.src, line_number, talloc_strdup(gd.src, line));
        line_no++;
    }
    fclose(f);
}
References itab_append(), gd::src, and src_clear().