Assign
Functions
Assign Assign_new (char *name, char *value)
Assigns Assigns_new (Assign assign, Assigns next)
void Assign_add (char *name, char *value)
Assign Assign_find (char *name)
char * Assign_value (Assign a)
char * Assign_name (Assign a)
void Assigns_dump (Assigns as)
Detailed Description
Function Documentation
Assign_add()
void Assign_add (char * name, char * value)
add an assignment pair to the global list. No additional checks are done.
                                           {
    Assign a = Assign_new(name, value);
    global_assigns = Assigns_new(a, global_assigns);
}
References Assign_new(), and Assigns_new().
Assign_find()
Assign Assign_find (char * name)
find a pair in the global assignment list with the given name
                                 {
    for(Assigns as = global_assigns; as; as = as->next) {
        if(strcmp(name, as->assign->name) == 0) {
            return as->assign;
        }
    }
    return NULL;
}
Assign_name()
char* Assign_name (Assign a)
return the name of the assignment pair
                              {
    return a->name;
}
Assign_new()
Assign Assign_new (char * name, char * value)
create new assignment pair
                                             {
    Assign result = malloc(sizeof(*result));
    result->name = strdup(name);
    result->value = strdup(value);
    return result;
}
Referenced by Assign_add().
Assign_value()
char* Assign_value (Assign a)
return the value of the assignment pair
                               {
    return a->value;
}
Assigns_dump()
void Assigns_dump (Assigns as)
dump the contents of the global assignment list
                                {
    for(; as; as = as->next) {
        printf("%s <- %s\n", as->assign->name, as->assign->value);
    }
}
Assigns_new()
Assigns Assigns_new (Assign assign, Assigns next)
create a new assignment list
                                                   {
    Assigns result = malloc(sizeof(*result));
    result->assign = assign;
    result->next = next;
    return result;
}
Referenced by Assign_add().