ITab
Data Structures
struct itab_entry
structure of an entry in the itab.
struct itab
structure of itab
struct itab_iter
iterator over elements of an itab.
Functions
int itab_lines (struct itab *itab)
struct itab * itab_new ()
create a new itab with default parameters.
int itab_entry_cmp (const void *aptr, const void *bptr)
compares the keys of two entries
void itab_append (struct itab *itab, const char *key, void *value)
void * itab_read (struct itab *itab, const char *key)
void itab_dump (struct itab *itab)
struct itab_iter * itab_foreach (struct itab *tab)
struct itab_iter * itab_next (struct itab_iter *iter)
void * itab_value (struct itab_iter *iter)
const char * itab_key (struct itab_iter *iter)
Detailed Description
sorted list of structures -> tables with primary index
Function Documentation
itab_append()
void itab_append (struct itab * itab, const char * key, void * value)
append new line
                                                                    {
    assert(itab != NULL);
    if(itab->total == itab->used) {
        itab->total *= 2;
        itab->rows =
                talloc_realloc(itab, itab->rows, struct itab_entry,
                                itab->total);
    }
    struct itab_entry *row = &itab->rows[itab->used];
    row->key = talloc_strdup(itab, key);
    row->value = value;
    itab->used++;
    qsort(itab->rows, // base
           itab->used, // nmemb
           sizeof(struct itab_entry), // size
           itab_entry_cmp);
}
References itab_entry_cmp(), itab_entry::key, rows, total, used, and itab_entry::value.
Referenced by class_enter(), method_enter(), src_add(), and src_read().
itab_dump()
void itab_dump (struct itab * itab)
dump content to output
                                    {
    assert(itab);
    for(int i = 0; i < itab->used; i++) {
        fprintf(stderr, "%s: %p\n", itab->rows[i].key, itab->rows[i].value);
    }
}
References itab_entry::key, rows, used, and itab_entry::value.
itab_entry_cmp()
int itab_entry_cmp (const void * aptr, const void * bptr)
compares the keys of two entries
compare entries
Returns
< 0, when first key is lower
== 0, when both keys are equal
> 0, when second key is lower
                                                         {
    const struct itab_entry *a = aptr;
    const struct itab_entry *b = bptr;
    return strcmp(a->key, b->key);
}
References itab_entry::key.
Referenced by itab_append(), and itab_read().
itab_foreach()
struct itab_iter * itab_foreach (struct itab * tab)
start iteration
                                                   {
    if(tab->used > 0) {
        struct itab_iter *r = talloc_zero(NULL, struct itab_iter);
        r->tab = tab;
        r->pos = 0;
        return r;
    }
    else
        return NULL;
}
References itab_iter::pos, itab_iter::tab, and used.
Referenced by readLine(), and src_dump().
itab_key()
const char * itab_key (struct itab_iter * iter)
key of current iterator
                                               {
    return iter->tab->rows[iter->pos].key;
}
References itab_entry::key, itab_iter::pos, rows, and itab_iter::tab.
Referenced by src_dump().
itab_lines()
unsigned itab_lines (struct itab * itab)
how many lines?
returns the number of lines in the table
                                         {
    assert(itab != NULL);
    return itab->used;
}
References used.
Referenced by src_add().
itab_new()
struct itab * itab_new (void)
create a new itab with default parameters.
new
Returns
reference to an itab structure.
Detailed description follows here.
                          {
    struct itab *r = talloc_zero(NULL, struct itab);
    r->total = 10;
    r->used = 0;
    r->rows = talloc_array(r, struct itab_entry, r->total);
    return r;
}
References rows, total, and used.
Referenced by require_classes(), and src_clear().
itab_next()
struct itab_iter * itab_next (struct itab_iter * iter)
cycle through iterator
                                                      {
    iter->pos++;
    if(iter->tab->used > iter->pos) {
        return iter;
    }
    else {
        talloc_free(iter);
        return NULL;
    }
}
References itab_iter::pos, itab_iter::tab, and used.
Referenced by readLine(), and src_dump().
itab_read()
void * itab_read (struct itab * itab, const char * key)
find a line by key
                                                      {
    assert(itab);
    assert(key);
    struct itab_entry dummy = { key, NULL };
    struct itab_entry *r = bsearch(&dummy,
                                    itab->rows,
                                    itab->used,
                                    sizeof(struct itab_entry),
                                    itab_entry_cmp);
    if(r)
        return r->value;
    else
        return NULL;
}
References itab_entry_cmp(), itab_entry::key, rows, used, and itab_entry::value.
Referenced by class_enter(), and method_enter().
itab_value()
void * itab_value (struct itab_iter * iter)
value of current iterator
                                           {
    return iter->tab->rows[iter->pos].value;
}
References itab_iter::pos, rows, itab_iter::tab, and itab_entry::value.
Referenced by readLine(), and src_dump().